version: "3"
services:
    php72-apache:
        image: anax/dev:php72-apache
        ports:
            - "10072:80"
        volumes:
            - .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
    php71-apache:
        image: anax/dev:php71-apache
        ports:
            - "10071:80"
        volumes:
            - .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
    php70-apache:
        image: anax/dev:php70-apache
        ports:
            - "10070:80"
        volumes:
            - .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
    php56-apache:
        image: anax/dev:php56-apache
        ports:
            - "10056:80"
        volumes:
            - .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
